library(data.table)
library(pROC)
library(ggplot2)
library(dplyr)
library(cowplot)
library(ggpubr)
library(rstatix)
#library(tidyverse)

# subgroup analysis

args <- commandArgs(TRUE)
infh <- args[1]
outfigprefix <- args[2]

new_plotstrataperf <- function(infh,outfigprefix) {
    fh <- fread(infh,header=TRUE,sep="\t",data.table=FALSE)
    dt <- fh %>% mutate(GAW_bin=cut(GA,breaks=c(0,83,90,105),labels=c("b12","d12","a12")))

    dt_b12 <- subset(dt,GAW_bin=="b12")
    dt_d12 <- subset(dt,GAW_bin=="d12")
    dt_a12 <- subset(dt,GAW_bin=="a12")

    dt_b12_perf <- roc(response=dt_b12$CaseCtrl,predictor=dt_b12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    dt_d12_perf <- roc(response=dt_d12$CaseCtrl,predictor=dt_d12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    dt_a12_perf <- roc(response=dt_a12$CaseCtrl,predictor=dt_a12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig11 <- paste0(outfigprefix,".entirecohort.strata_GAweek.roc.pdf")
    pdf(outfig11,height=6.5,width=6.5)
    plot(dt_b12_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(dt_d12_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    plot(dt_a12_perf,col="#7570b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.3,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("before wk12","during wk12","after wk12"),col=c("#1b9e77","#d95f02","#7570b3"),lwd=3,cex=1)
    dev.off()

    outfig12 <- paste0(outfigprefix,".entirecohort.strata_GAweek.boxplot.pdf")
    dt$CaseCtrl <- factor(dt$CaseCtrl,levels=c("Ctrl","Case"))
    dt$GAW_bin <- factor(dt$GAW_bin,levels=c("b12","d12","a12"))
    plotdt <- dt %>% group_by(GAW_bin,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    GAWlabels <- c(b12="Before wk12",d12="During wk12",a12="After wk12")
    stat.test <- dt %>% group_by(GAW_bin) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig12,height=5.5,width=7.8)
    p12 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="Gestational week at sampling",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(GAW_bin),labeller=labeller(GAW_bin=GAWlabels))+stat_pvalue_manual(stat.test)
    print(p12)
    dev.off()

    dt_bmi1 <- subset(dt,BMIgroup=="lt25")
    dt_bmi2 <- subset(dt,BMIgroup=="gte25")

    dt_bmi1_perf <- roc(response=dt_bmi1$CaseCtrl,predictor=dt_bmi1$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    dt_bmi2_perf <- roc(response=dt_bmi2$CaseCtrl,predictor=dt_bmi2$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig91 <- paste0(outfigprefix,".entirecohort.strata_BMIgroup.roc.pdf")
    pdf(outfig91,height=6.5,width=6.5)
    plot(dt_bmi1_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(dt_bmi2_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("BMI < 25","BMI >= 25"),col=c("#1b9e77","#d95f02"),lwd=3,cex=1)
    dev.off()

    outfig92 <- paste0(outfigprefix,".entirecohort.strata_BMIgroup.boxplot.pdf")
    dt$CaseCtrl <- factor(dt$CaseCtrl,levels=c("Ctrl","Case"))
    dt$BMIgroup <- factor(dt$BMIgroup,levels=c("lt25","gte25"))
    plotdt <- dt %>% group_by(BMIgroup,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    BMIlabels <- c(lt25="BMI < 25",gte25="BMI >= 25")
    stat.test <- dt %>% group_by(BMIgroup) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig92,height=5.5,width=7.8)
    p92 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="BMI",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(BMIgroup),labeller=labeller(BMIgroup=BMIlabels))+stat_pvalue_manual(stat.test)
    print(p92)

    dt_null <- subset(dt,Obstretrical.history=="Nullip")
    dt_multino <- subset(dt,Obstretrical.history=="Multip-no PE")
    dt_multiyes <- subset(dt,Obstretrical.history=="Multip-PE")

    dt_null_perf <- roc(response=dt_null$CaseCtrl,predictor=dt_null$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    dt_multino_perf <- roc(response=dt_multino$CaseCtrl,predictor=dt_multino$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    dt_multiyes_perf <- roc(response=dt_multiyes$CaseCtrl,predictor=dt_multiyes$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig31 <- paste0(outfigprefix,".entirecohort.strata_Parity.roc.pdf")
    pdf(outfig31,height=6.5,width=6.5)
    plot(dt_null_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(dt_multino_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    plot(dt_multiyes_perf,col="#7570b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.3,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("Nulliparity","Multiparity No PE","Multiparity had PE"),col=c("#1b9e77","#d95f02","#7570b3"),lwd=3,cex=1)
    dev.off()

    outfig32 <- paste0(outfigprefix,".entirecohort.strata_Parity.boxplot.pdf")
    pdt <- subset(dt,Obstretrical.history!="NA")
    pdt$CaseCtrl <- factor(pdt$CaseCtrl,levels=c("Ctrl","Case"))
    pdt$Obstretrical.history <- factor(pdt$Obstretrical.history,levels=c("Nullip","Multip-no PE","Multip-PE"))
    plotdt <- pdt %>% group_by(Obstretrical.history,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    Histlabels <- c(Nullip="Nulliparity",`Multip-no PE`="Multiparity No PE",`Multip-PE`="Multiparity had PE")
    stat.test <- pdt %>% group_by(Obstretrical.history) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig32,height=5.5,width=7.8)
    p32 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="Parity",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(Obstretrical.history),labeller=labeller(Obstretrical.history=Histlabels))+stat_pvalue_manual(stat.test)
    print(p32)
    dev.off()

    ###assisted reproduction
    dt_spon <- subset(dt,MoConception3=="Spontaneous")
    dt_ivf <- subset(dt,MoConception3=="IVF")

    dt_spon_perf <- roc(response=dt_spon$CaseCtrl,predictor=dt_spon$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    dt_ivf_perf <- roc(response=dt_ivf$CaseCtrl,predictor=dt_ivf$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig41 <- paste0(outfigprefix,".entirecohort.strata_Conception.roc.pdf")
    pdf(outfig41,height=6.5,width=6.5)
    plot(dt_spon_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(dt_ivf_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("Spontaneous","IVF"),col=c("#1b9e77","#d95f02"),lwd=3,cex=1)
    dev.off()

    outfig42 <- paste0(outfigprefix,".entirecohort.strata_Conception.boxplot.pdf")
    cdt <- subset(dt,MoConception3!="NA")
    cdt$CaseCtrl <- factor(cdt$CaseCtrl,levels=c("Ctrl","Case"))
    cdt$MoConception3 <- factor(cdt$MoConception3,levels=c("Spontaneous","IVF"))
    plotdt <- cdt %>% group_by(MoConception3,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    conlabels <- c(Spontaneous="Spontaneous",IVF="IVF")
    stat.test <- cdt %>% group_by(MoConception3) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig42,height=5.5,width=7.8)
    p42 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="Conception",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(MoConception3),labeller=labeller(MoConception3=conlabels))+stat_pvalue_manual(stat.test)
    print(p42)
    dev.off()

    ###Twin
    outfig52 <- paste0(outfigprefix,".entirecohort.strata_Twin.boxplot.pdf")
    dt <- dt %>% mutate(Twingroup = if_else(Singleton.Twin=="Singleton","Singleton","Twin"))
    dt$CaseCtrl <- factor(dt$CaseCtrl,levels=c("Ctrl","Case"))
    dt$Twingroup <- factor(dt$Twingroup,levels=c("Singleton","Twin"))
    plotdt <- dt %>% group_by(Twingroup,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    twinlabels <- c(Singleton="Singleton",Twin="Twin")
    #stat.test <- dt %>% group_by(Twingroup) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig52,height=5.5,width=7.8)
    p52 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="Singleton",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(Twingroup),labeller=labeller(Twingroup=twinlabels))
    print(p52)
    dev.off()

    ###Severity
    dt_sevyes <- subset(dt,!(CaseCtrl == "Case" & Severe == 0))
    dt_sevno <- subset(dt,!(CaseCtrl == "Case" & Severe == 1))

    dt_sevyes_perf <- roc(response=dt_sevyes$CaseCtrl,predictor=dt_sevyes$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    dt_sevno_perf <- roc(response=dt_sevno$CaseCtrl,predictor=dt_sevno$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig71 <- paste0(outfigprefix,".entirecohort.strata_Severity.roc.pdf")
    pdf(outfig71,height=6.5,width=6.5)
    plot(dt_sevyes_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(dt_sevno_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("With severe feature","Without severe feature"),col=c("#1b9e77","#d95f02"),lwd=3,cex=1)
    dev.off()
    
    ##combine subgroups
    outfigPP <- paste0(outfigprefix,".entirecohort.case_strata.boxplot.pdf")
    pdf(outfigPP,height=4.5,width=9.8)
    dt$CaseCtrl <- factor(dt$CaseCtrl,levels=c("Ctrl","Case"))
    plotdt1 <- dt %>% group_by(CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    stat.test0 <- dt %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    stat.test0 %>% print(n=Inf)
    dt %>% group_by(CaseCtrl) %>% summarise(median = median(PEscore, na.rm = TRUE)) %>% print(n=Inf)
    comp1 <- ggplot(plotdt1,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=11,angle=45,vjust=0.5,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="All samples",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))

    GAWdt <- subset(dt,CaseCtrl=="Case")
    GAWdt <- GAWdt %>% mutate(GAW_bin=cut(GA,breaks=c(0,83,90,105),labels=c("b12","d12","a12")))
    GAWdt$GAW_bin <- factor(GAWdt$GAW_bin,levels=c("b12","d12","a12"))
    plotdt2 <- GAWdt %>% group_by(GAW_bin) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    stat.test1 <- GAWdt %>% wilcox_test(PEscore ~ GAW_bin) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_y_position()
    #print(stat.test1)
    stat.test1 %>% print(n=Inf)
    GAWdt %>% group_by(GAW_bin) %>% summarise(median = median(PEscore, na.rm = TRUE)) %>% print(n=Inf)
    comp2 <- ggplot(plotdt2,aes(x=GAW_bin,y=PEscore))+geom_boxplot(position=position_dodge(1),color="royalblue4")+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),fill="royalblue4")+theme_bw()+theme(axis.text.x=element_text(size=11,angle=45,vjust=0.5,color="black"),legend.text=element_text(size=14),axis.title.x=element_text(size=14,color="black"),axis.text.y=element_blank(),axis.title.y=element_blank(),axis.ticks.y=element_blank(),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=GAW_bin,y=0,label=Nobs),color="black")+labs(x="Gestation",y="cfDNAme score")+scale_x_discrete(labels=c("b12"="Before wk12","d12"="During wk12","a12"="After wk12"))

    BMIdt <- subset(dt,CaseCtrl=="Case")
    BMIdt$BMIgroup <- factor(BMIdt$BMIgroup,levels=c("lt25","gte25"))
    plotdt3 <- BMIdt %>% group_by(BMIgroup) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    stat.test2 <- BMIdt %>% wilcox_test(PEscore ~ BMIgroup) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_y_position()
    #print(stat.test2)
    stat.test2 %>% print(n=Inf)
    BMIdt %>% group_by(BMIgroup) %>% summarise(median = median(PEscore, na.rm = TRUE)) %>% print(n=Inf)
    comp3 <- ggplot(plotdt3,aes(x=BMIgroup,y=PEscore))+geom_boxplot(position=position_dodge(1),color="royalblue4")+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),fill="royalblue4")+theme_bw()+theme(axis.text.x=element_text(size=11,angle=45,vjust=0.5,color="black"),legend.text=element_text(size=14),axis.title.x=element_text(size=14,color="black"),axis.text.y=element_blank(),axis.title.y=element_blank(),axis.ticks.y=element_blank(),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=BMIgroup,y=0,label=Nobs),color="black")+labs(x="BMI",y="cfDNAme score")+scale_x_discrete(labels=c("lt25"="< 25","gte25"=">= 25"))

    pdt <- subset(dt,Obstretrical.history!="NA")
    paritydt <- subset(pdt,CaseCtrl=="Case")
    paritydt$Obstretrical.history <- factor(paritydt$Obstretrical.history,levels=c("Nullip","Multip-no PE","Multip-PE"))
    plotdt4 <- paritydt %>% group_by(Obstretrical.history) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    stat.test3 <- paritydt %>% wilcox_test(PEscore ~ Obstretrical.history) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_y_position()
    #print(stat.test3)
    stat.test3 %>% print(n=Inf)
    paritydt %>% group_by(Obstretrical.history) %>% summarise(median = median(PEscore, na.rm = TRUE)) %>% print(n=Inf)
    comp4 <- ggplot(plotdt4,aes(x=Obstretrical.history,y=PEscore))+geom_boxplot(position=position_dodge(1),color="royalblue4")+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),fill="royalblue4")+theme_bw()+theme(axis.text.x=element_text(size=11,angle=45,vjust=0.5,color="black"),legend.text=element_text(size=14),axis.title.x=element_text(size=14,color="black"),axis.text.y=element_blank(),axis.title.y=element_blank(),axis.ticks.y=element_blank(),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=Obstretrical.history,y=0,label=Nobs),color="black")+labs(x="Parity",y="cfDNAme score")+scale_x_discrete(labels=c("Nullip"="Null","Multip-no PE"="Multi noPE","Multip-PE"="Multi PE"))
		
    idt <- subset(dt,IUGR=="Yes" | IUGR=="No")
    iudt <- subset(idt,CaseCtrl=="Case")
    iudt$IUGR <- factor(iudt$IUGR,levels=c("Yes","No"))
    plotdt5 <- iudt %>% group_by(IUGR) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    stat.test4 <- iudt %>% wilcox_test(PEscore ~ IUGR) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_y_position()
    #print(stat.test4)
    stat.test4 %>% print(n=Inf)
    iudt %>% group_by(IUGR) %>% summarise(median = median(PEscore, na.rm = TRUE)) %>% print(n=Inf)
    comp5 <- ggplot(plotdt5,aes(x=IUGR,y=PEscore))+geom_boxplot(position=position_dodge(1),color="royalblue4")+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),fill="royalblue4")+theme_bw()+theme(axis.text.x=element_text(size=11,angle=45,vjust=0.5,color="black"),legend.text=element_text(size=14),axis.title.x=element_text(size=14,color="black"),axis.text.y=element_blank(),axis.title.y=element_blank(),axis.ticks.y=element_blank(),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=IUGR,y=0,label=Nobs),color="black")+labs(x="IUGR",y="cfDNAme score")+scale_x_discrete(labels=c("Yes"="Yes","No"="No"))

    cdt <- subset(dt,MoConception3!="NA")
    concepdt <- subset(cdt,CaseCtrl=="Case")
    concepdt$MoConception3 <- factor(concepdt$MoConception3,levels=c("Spontaneous","IVF"))
    plotdt6 <- concepdt %>% group_by(MoConception3) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    stat.test5 <- concepdt %>% wilcox_test(PEscore ~ MoConception3) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_y_position()
    stat.test5 %>% print(n=Inf)
    concepdt %>% group_by(MoConception3) %>% summarise(median=median(PEscore,na.rm=TRUE)) %>% print(n=Inf)
    comp6 <- ggplot(plotdt6,aes(x=MoConception3,y=PEscore))+geom_boxplot(position=position_dodge(1),color="royalblue4")+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),fill="royalblue4")+theme_bw()+theme(axis.text.x=element_text(size=11,angle=45,vjust=0.5,color="black"),legend.text=element_text(size=14),axis.title.x=element_text(size=14,color="black"),axis.text.y=element_blank(),axis.title.y=element_blank(),axis.ticks.y=element_blank(),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=MoConception3,y=0,label=Nobs),color="black")+labs(x="Conception",y="cfDNAme score")+scale_x_discrete(labels=c("Spontaneous"="Spontaneous","IVF"="IVF"))

    twdt <- subset(dt,CaseCtrl=="Case")
    twdt$Twingroup <- ifelse(twdt$Singleton.Twin=="Singleton", "Singleton", "Twin")
    twdt$Twingroup <- factor(twdt$Twingroup,levels=c("Singleton","Twin"))
    plotdt7 <- twdt %>% group_by(Twingroup) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    stat.test6 <- twdt %>% wilcox_test(PEscore ~ Twingroup) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_y_position()
    stat.test6 %>% print(n=Inf)
    twdt %>% group_by(Twingroup) %>% summarise(median=median(PEscore,na.rm=TRUE)) %>% print(n=Inf)
    comp7 <- ggplot(plotdt7,aes(x=Twingroup,y=PEscore))+geom_boxplot(position=position_dodge(1),color="royalblue4")+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),fill="royalblue4")+theme_bw()+theme(axis.text.x=element_text(size=11,angle=45,vjust=0.5,color="black"),legend.text=element_text(size=14),axis.title.x=element_text(size=14,color="black"),axis.text.y=element_blank(),axis.title.y=element_blank(),legend.position="none",axis.ticks.y=element_blank(),strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=Twingroup,y=0,label=Nobs),color="black")+labs(x="Singleton",y="cfDNAme score")+scale_x_discrete(labels=c("Singleton"="Singleton","Twin"="Twin"))

    sedt <- subset(dt,CaseCtrl=="Case")
    sedt$Severity <- ifelse(sedt$Severe=="1","Yes","No")
    sedt$Severity <- factor(sedt$Severity,levels=c("Yes","No"))
    plotdt8 <- sedt %>% group_by(Severity) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    stat.test7 <- sedt %>% wilcox_test(PEscore ~ Severity) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_y_position()
    stat.test7 %>% print(n=Inf)
    sedt %>% group_by(Severity) %>% summarise(median=median(PEscore,na.rm=TRUE)) %>% print(n=Inf)
    comp8 <- ggplot(plotdt8,aes(x=Severity,y=PEscore))+geom_boxplot(position=position_dodge(1),color="royalblue4")+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),fill="royalblue4")+theme_bw()+theme(axis.text.x=element_text(size=11,angle=45,vjust=0.5,color="black"),legend.text=element_text(size=14),axis.title.x=element_text(size=14,color="black"),axis.text.y=element_blank(),axis.title.y=element_blank(),legend.position="none",axis.ticks.y=element_blank(),strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=Severity,y=0,label=Nobs),color="black")+labs(x="Severity",y="cfDNAme score")+scale_x_discrete(labels=c("Yes"="Yes","No"="No"))

    pp <- plot_grid(comp1,comp2,comp3,comp4,comp5,comp6,comp7,comp8,align="h",rel_widths=c(1.2,1.2,0.8,1.2,0.8,0.8,0.8,0.8),nrow=1)
    print(pp)
    dev.off()
}

new_plotstrataperf(infh,outfigprefix)

plotstrataperf <- function(infh,outfigprefix) {
    fh <- fread(infh,header=TRUE,sep="\t",data.table=FALSE)
    dt <- fh %>% mutate(GAW_bin=cut(GA,breaks=c(0,83,90,105),labels=c("b12","d12","a12")))
    print(head(dt))

    tdt <- subset(dt,TrainValidation=="Training")
    vdt <- subset(dt,TrainValidation=="Validation")

    ##statify by GA weeks
    tdt_b12 <- subset(tdt,GAW_bin=="b12")
    tdt_d12 <- subset(tdt,GAW_bin=="d12")
    tdt_a12 <- subset(tdt,GAW_bin=="a12")
    
    tdt_b12_perf <- roc(response=tdt_b12$CaseCtrl,predictor=tdt_b12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    tdt_d12_perf <- roc(response=tdt_d12$CaseCtrl,predictor=tdt_d12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    tdt_a12_perf <- roc(response=tdt_a12$CaseCtrl,predictor=tdt_a12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig11 <- paste0(outfigprefix,".discovery.strata_GAweek.roc.pdf")
    pdf(outfig11,height=6.5,width=6.5)
    plot(tdt_b12_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(tdt_d12_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    plot(tdt_a12_perf,col="#7570b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.3,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("before wk12","during wk12","after wk12"),col=c("#1b9e77","#d95f02","#7570b3"),lwd=3,cex=1)
    dev.off()

    outfig12 <- paste0(outfigprefix,".discovery.strata_GAweek.boxplot.pdf")
    tdt$CaseCtrl <- factor(tdt$CaseCtrl,levels=c("Ctrl","Case"))
    tdt$GAW_bin <- factor(tdt$GAW_bin,levels=c("b12","d12","a12"))
    plotdt <- tdt %>% group_by(GAW_bin,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    GAWlabels <- c(b12="Before wk12",d12="During wk12",a12="After wk12")
    stat.test <- tdt %>% group_by(GAW_bin) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig12,height=5.5,width=7.8)
    p12 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="Gestational week at sampling",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(GAW_bin),labeller=labeller(GAW_bin=GAWlabels))+stat_pvalue_manual(stat.test)
    print(p12)
    dev.off()

    vdt_b12 <- subset(vdt,GAW_bin=="b12")
    vdt_d12 <- subset(vdt,GAW_bin=="d12")
    vdt_a12 <- subset(vdt,GAW_bin=="a12")

    vdt_b12_perf <- roc(response=vdt_b12$CaseCtrl,predictor=vdt_b12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    vdt_d12_perf <- roc(response=vdt_d12$CaseCtrl,predictor=vdt_d12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    vdt_a12_perf <- roc(response=vdt_a12$CaseCtrl,predictor=vdt_a12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    
    outfig21 <- paste0(outfigprefix,".validation.strata_GAweek.roc.pdf")
    pdf(outfig21,height=6.5,width=6.5)
    plot(vdt_b12_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(vdt_d12_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    plot(vdt_a12_perf,col="#7570b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.3,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("before wk12","during wk12","after wk12"),col=c("#1b9e77","#d95f02","#7570b3"),lwd=3,cex=1)
    dev.off()

    outfig22 <- paste0(outfigprefix,".validation.strata_GAweek.boxplot.pdf")
    vdt$CaseCtrl <- factor(vdt$CaseCtrl,levels=c("Ctrl","Case"))
    vdt$GAW_bin <- factor(vdt$GAW_bin,levels=c("b12","d12","a12"))
    plotdt <- vdt %>% group_by(GAW_bin,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    GAWlabels <- c(b12="Before wk12",d12="During wk12",a12="After wk12")
    stat.test <- vdt %>% group_by(GAW_bin) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig22,height=5.5,width=7.8)
    p22 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="Gestational week at sampling",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(GAW_bin),labeller=labeller(GAW_bin=GAWlabels))+stat_pvalue_manual(stat.test)
    print(p22)
    dev.off()

    ##stratify by BMIgroup
    tdt_bmi1 <- subset(tdt,BMIgroup=="lt25")
    tdt_bmi2 <- subset(tdt,BMIgroup=="gte25")

    tdt_bmi1_perf <- roc(response=tdt_bmi1$CaseCtrl,predictor=tdt_bmi1$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    tdt_bmi2_perf <- roc(response=tdt_bmi2$CaseCtrl,predictor=tdt_bmi2$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig91 <- paste0(outfigprefix,".discovery.strata_BMIgroup.roc.pdf")
    pdf(outfig91,height=6.5,width=6.5)
    plot(tdt_bmi1_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(tdt_bmi2_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("BMI < 25","BMI >= 25"),col=c("#1b9e77","#d95f02"),lwd=3,cex=1)
    dev.off()

    outfig92 <- paste0(outfigprefix,".discovery.strata_BMIgroup.boxplot.pdf")
    tdt$CaseCtrl <- factor(tdt$CaseCtrl,levels=c("Ctrl","Case"))
    tdt$BMIgroup <- factor(tdt$BMIgroup,levels=c("lt25","gte25"))
    plotdt <- tdt %>% group_by(BMIgroup,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    BMIlabels <- c(lt25="BMI < 25",gte25="BMI >= 25")
    stat.test <- tdt %>% group_by(BMIgroup) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig92,height=5.5,width=7.8)
    p92 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="BMI",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(BMIgroup),labeller=labeller(BMIgroup=BMIlabels))+stat_pvalue_manual(stat.test)
    print(p92)

    vdt_bmi1 <- subset(vdt,BMIgroup=="lt25")
    vdt_bmi2 <- subset(vdt,BMIgroup=="gte25")
    
    vdt_bmi1_perf <- roc(response=vdt_bmi1$CaseCtrl,predictor=vdt_bmi1$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    vdt_bmi2_perf <- roc(response=vdt_bmi2$CaseCtrl,predictor=vdt_bmi2$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig93 <- paste0(outfigprefix,".validation.strata_BMIgroup.roc.pdf")
    pdf(outfig93,height=6.5,width=6.5)
    plot(vdt_bmi1_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(vdt_bmi2_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("BMI < 25","BMI >= 25"),col=c("#1b9e77","#d95f02"),lwd=3,cex=1)
    dev.off()

    outfig94 <- paste0(outfigprefix,".validation.strata_BMIgroup.boxplot.pdf")
    vdt$CaseCtrl <- factor(vdt$CaseCtrl,levels=c("Ctrl","Case"))
    vdt$BMIgroup <- factor(vdt$BMIgroup,levels=c("lt25","gte25"))
    plotdt <- vdt %>% group_by(BMIgroup,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    BMIlabels <- c(lt25="BMI < 25",gte25="BMI >= 25")
    stat.test <- vdt %>% group_by(BMIgroup) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig94,height=5.5,width=7.8)
    p94 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="BMI",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(BMIgroup),labeller=labeller(BMIgroup=BMIlabels))+stat_pvalue_manual(stat.test)
    print(p94)
    dev.off()
    
    ##stratify by parity
    tdt_null <- subset(tdt,Obstretrical.history=="Nullip")
    tdt_multino <- subset(tdt,Obstretrical.history=="Multip-no PE")
    tdt_multiyes <- subset(tdt,Obstretrical.history=="Multip-PE")

    tdt_null_perf <- roc(response=tdt_null$CaseCtrl,predictor=tdt_null$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    tdt_multino_perf <- roc(response=tdt_multino$CaseCtrl,predictor=tdt_multino$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    tdt_multiyes_perf <- roc(response=tdt_multiyes$CaseCtrl,predictor=tdt_multiyes$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig31 <- paste0(outfigprefix,".discovery.strata_Parity.roc.pdf")
    pdf(outfig31,height=6.5,width=6.5)
    plot(tdt_null_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(tdt_multino_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    plot(tdt_multiyes_perf,col="#7570b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.3,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("Nulliparity","Multiparity No PE","Multiparity had PE"),col=c("#1b9e77","#d95f02","#7570b3"),lwd=3,cex=1)
    dev.off()

    outfig32 <- paste0(outfigprefix,".discovery.strata_Parity.boxplot.pdf")
    pdt <- subset(tdt,Obstretrical.history!="NA")
    pdt$CaseCtrl <- factor(pdt$CaseCtrl,levels=c("Ctrl","Case"))
    pdt$Obstretrical.history <- factor(pdt$Obstretrical.history,levels=c("Nullip","Multip-no PE","Multip-PE"))
    plotdt <- pdt %>% group_by(Obstretrical.history,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    Histlabels <- c(Nullip="Nulliparity",`Multip-no PE`="Multiparity No PE",`Multip-PE`="Multiparity had PE")
    stat.test <- pdt %>% group_by(Obstretrical.history) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig32,height=5.5,width=7.8)
    p32 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="Parity",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(Obstretrical.history),labeller=labeller(Obstretrical.history=Histlabels))+stat_pvalue_manual(stat.test)
    print(p32)
    dev.off()


    vdt_null <- subset(vdt,Obstretrical.history=="Nullip")
    vdt_multino <- subset(vdt,Obstretrical.history=="Multip-no PE")
    vdt_multiyes <- subset(vdt,Obstretrical.history=="Multip-PE")
    vdt_null_perf <- roc(response=vdt_null$CaseCtrl,predictor=vdt_null$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    vdt_multino_perf <- roc(response=vdt_multino$CaseCtrl,predictor=vdt_multino$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    vdt_multiyes_perf <- roc(response=vdt_multiyes$CaseCtrl,predictor=vdt_multiyes$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig33 <- paste0(outfigprefix,".validation.strata_Parity.roc.pdf")
    pdf(outfig33,height=6.5,width=6.5)
    plot(vdt_null_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(vdt_multino_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    plot(vdt_multiyes_perf,col="#7570b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.3,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("Nulliparity","Multiparity No PE","Multiparity had PE"),col=c("#1b9e77","#d95f02","#7570b3"),lwd=3,cex=1)
    dev.off()

    outfig34 <- paste0(outfigprefix,".validation.strata_Parity.boxplot.pdf")
    pdt <- subset(vdt,Obstretrical.history!="NA")
    pdt$CaseCtrl <- factor(pdt$CaseCtrl,levels=c("Ctrl","Case"))
    pdt$Obstretrical.history <- factor(pdt$Obstretrical.history,levels=c("Nullip","Multip-no PE","Multip-PE"))
    plotdt <- pdt %>% group_by(Obstretrical.history,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    Histlabels <- c(Nullip="Nulliparity",`Multip-no PE`="Multiparity No PE",`Multip-PE`="Multiparity had PE")
    stat.test <- pdt %>% group_by(Obstretrical.history) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig34,height=5.5,width=7.8)
    p34 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="Parity",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(Obstretrical.history),labeller=labeller(Obstretrical.history=Histlabels))+stat_pvalue_manual(stat.test)
    print(p34)
    dev.off()

    ##stratify by IUGR
    itdt <- subset(tdt,IUGR=="Yes" | IUGR=="No")
    itdt_IUGRno <- subset(itdt,IUGR=="No")
    itdt_IUGRyes <- subset(itdt,IUGR=="Yes")

    itdt_IUGRno_perf <- roc(response=itdt_IUGRno$CaseCtrl,predictor=itdt_IUGRno$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    itdt_IUGRyes_perf <- roc(response=itdt_IUGRyes$CaseCtrl,predictor=itdt_IUGRyes$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig51 <- paste0(outfigprefix,".discovery.strata_IUGR.roc.pdf")
    pdf(outfig51,height=6.5,width=6.5)
    plot(itdt_IUGRno_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(itdt_IUGRyes_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("Without IUGR","With IUGR"),col=c("#1b9e77","#d95f02"),lwd=3,cex=1)
    dev.off()

    outfig52 <- paste0(outfigprefix,".discovery.strata_IUGR.boxplot.pdf")
    itdt$CaseCtrl <- factor(itdt$CaseCtrl,levels=c("Ctrl","Case"))
    itdt$IUGR <- factor(itdt$IUGR,levels=c("No","Yes"))
    plotdt <- itdt %>% group_by(IUGR,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    iugrlabels <- c(No="No",Yes="Yes")
    stat.test <- itdt %>% group_by(IUGR) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig52,height=5.5,width=7.8)
    p52 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="IUGR",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(IUGR),labeller=labeller(IUGR=iugrlabels))+stat_pvalue_manual(stat.test)
    print(p52)
    dev.off()

    itdt <- subset(vdt,IUGR=="Yes" | IUGR=="No")
    itdt_IUGRno <- subset(itdt,IUGR=="No")
    itdt_IUGRyes <- subset(itdt,IUGR=="Yes")

    itdt_IUGRno_perf <- roc(response=itdt_IUGRno$CaseCtrl,predictor=itdt_IUGRno$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    itdt_IUGRyes_perf <- roc(response=itdt_IUGRyes$CaseCtrl,predictor=itdt_IUGRyes$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig53 <- paste0(outfigprefix,".validation.strata_IUGR.roc.pdf")
    pdf(outfig53,height=6.5,width=6.5)
    plot(itdt_IUGRno_perf,col="#1b9e77",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(itdt_IUGRyes_perf,col="#d95f02",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("Without IUGR","With IUGR"),col=c("#1b9e77","#d95f02"),lwd=3,cex=1)
    dev.off()

    outfig54 <- paste0(outfigprefix,".validation.strata_IUGR.boxplot.pdf")
    itdt$CaseCtrl <- factor(itdt$CaseCtrl,levels=c("Ctrl","Case"))
    itdt$IUGR <- factor(itdt$IUGR,levels=c("No","Yes"))
    plotdt <- itdt %>% group_by(IUGR,CaseCtrl) %>% mutate(N=n()) %>% mutate(Nobs=paste0('N=',N))
    iugrlabels <- c(No="No",Yes="Yes")
    stat.test <- itdt %>% group_by(IUGR) %>% wilcox_test(PEscore ~ CaseCtrl) %>% adjust_pvalue(method = "bonferroni") %>% add_significance() %>% add_xy_position(x = "CaseCtrl")
    pdf(outfig54,height=5.5,width=7.8)
    p54 <- ggplot(plotdt,aes(x=CaseCtrl,y=PEscore,color=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1),aes(fill=CaseCtrl))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"),legend.position="none",strip.text=element_text(size=12,face="bold"),strip.background=element_rect(fill="white"))+geom_text(aes(x=CaseCtrl,y=0,label=Nobs),color="black")+scale_color_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+scale_fill_manual(values=c("gray70","royalblue4"))+labs(x="IUGR",y="cfDNAme score")+scale_x_discrete(labels=c("Ctrl"="Control","Case"="PE"))+facet_grid(cols = vars(IUGR),labeller=labeller(IUGR=iugrlabels))+stat_pvalue_manual(stat.test)
    print(p54)
    dev.off()
}

plotstrataperf(infh,outfigprefix)



obs_plotstrataperf <- function(infh,outfigprefix) {
    fh <- fread(infh,header=TRUE,sep="\t",data.table=FALSE)
    dt <- fh %>% mutate(GAW_bin=cut(GA,breaks=c(0,83,90,105),labels=c("b12","d12","a12")))
    print(head(dt))

    tdt <- subset(dt,TrainValidation=="Training")
    vdt <- subset(dt,TrainValidation=="Validation")

    ##statify by GA weeks
    tdt_b12 <- subset(tdt,GAW_bin=="b12")
    tdt_d12 <- subset(tdt,GAW_bin=="d12")
    tdt_a12 <- subset(tdt,GAW_bin=="a12")
    print("train GAW b12 case")
    print(dim(tdt_b12[tdt_b12$CaseCtrl=="Case",]))
    print("train GAW b12 ctrl")
    print(dim(tdt_b12[tdt_b12$CaseCtrl=="Ctrl",]))
    print("train GAW d12 case")
    print(dim(tdt_d12[tdt_d12$CaseCtrl=="Case",]))
    print("train GAW d12 ctrl")
    print(dim(tdt_d12[tdt_d12$CaseCtrl=="Ctrl",]))
    print("train GAW a12 case")
    print(dim(tdt_a12[tdt_a12$CaseCtrl=="Case",]))
    print("train GAW a12 ctrl")
    print(dim(tdt_a12[tdt_a12$CaseCtrl=="Ctrl",]))
    
    tdt_b12_perf <- roc(response=tdt_b12$CaseCtrl,predictor=tdt_b12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    tdt_d12_perf <- roc(response=tdt_d12$CaseCtrl,predictor=tdt_d12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    tdt_a12_perf <- roc(response=tdt_a12$CaseCtrl,predictor=tdt_a12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig11 <- paste0(outfigprefix,".discovery.strata_GAweek.roc.pdf")
    pdf(outfig11,height=6.5,width=6.5)
    plot(tdt_b12_perf,col="#b3b3b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(tdt_d12_perf,col="#ffd92f",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    plot(tdt_a12_perf,col="#a6d854",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.3,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("before wk12","during wk12","after wk12"),col=c("#b3b3b3","#ffd92f","#a6d854"),lwd=3,cex=1)
    dev.off()

    outfig12 <- paste0(outfigprefix,".discovery.strata_GAweek.boxplot.pdf")
    tdt$CaseCtrl <- factor(tdt$CaseCtrl,levels=c("Ctrl","Case"))
    tdt$GAW_bin <- factor(tdt$GAW_bin,levels=c("b12","d12","a12"))
    pdf(outfig12,height=6.5,width=7.8)
    p12 <- ggplot(tdt,aes(x=GAW_bin,y=PEscore,fill=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"))+scale_fill_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+labs(x="Gestational week at sampling",y="cfDNAme score")+scale_x_discrete(labels=c("Before wk12","During wk12","After wk12"))
    print(p12)
    dev.off()

    vdt_b12 <- subset(vdt,GAW_bin=="b12")
    vdt_d12 <- subset(vdt,GAW_bin=="d12")
    vdt_a12 <- subset(vdt,GAW_bin=="a12")
    print("valid GAW b12 case")
    print(dim(vdt_b12[vdt_b12$CaseCtrl=="Case",]))
    print("valid GAW b12 ctrl")
    print(dim(vdt_b12[vdt_b12$CaseCtrl=="Ctrl",]))
    print("valid GAW d12 case")
    print(dim(vdt_d12[vdt_d12$CaseCtrl=="Case",]))
    print("valid GAW d12 ctrl")
    print(dim(vdt_d12[vdt_d12$CaseCtrl=="Ctrl",]))
    print("valid GAW a12 case")
    print(dim(vdt_a12[vdt_a12$CaseCtrl=="Case",]))
    print("valid GAW a12 ctrl")
    print(dim(vdt_a12[vdt_a12$CaseCtrl=="Ctrl",]))

    vdt_b12_perf <- roc(response=vdt_b12$CaseCtrl,predictor=vdt_b12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    vdt_d12_perf <- roc(response=vdt_d12$CaseCtrl,predictor=vdt_d12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    vdt_a12_perf <- roc(response=vdt_a12$CaseCtrl,predictor=vdt_a12$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    
    outfig21 <- paste0(outfigprefix,".validation.strata_GAweek.roc.pdf")
    pdf(outfig21,height=6.5,width=6.5)
    plot(vdt_b12_perf,col="#b3b3b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(vdt_d12_perf,col="#ffd92f",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    plot(vdt_a12_perf,col="#a6d854",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.3,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("before wk12","during wk12","after wk12"),col=c("#b3b3b3","#ffd92f","#a6d854"),lwd=3,cex=1)
    dev.off()

    outfig22 <- paste0(outfigprefix,".validation.strata_GAweek.boxplot.pdf")
    vdt$CaseCtrl <- factor(vdt$CaseCtrl,levels=c("Ctrl","Case"))
    vdt$GAW_bin <- factor(vdt$GAW_bin,levels=c("b12","d12","a12"))
    pdf(outfig22,height=6.5,width=7.8)
    p22 <- ggplot(vdt,aes(x=GAW_bin,y=PEscore,fill=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"))+scale_fill_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+labs(x="Gestational week at sampling",y="cfDNAme score")+scale_x_discrete(labels=c("Before wk12","During wk12","After wk12"))
    print(p22)
    dev.off()

    ##stratify by BMIgroup
    tdt_bmi1 <- subset(tdt,BMIgroup=="lt25")
    tdt_bmi2 <- subset(tdt,BMIgroup=="gte25")
    print("train bmi lt25 case")
    print(dim(tdt_bmi1[tdt_bmi1$CaseCtrl=="Case",]))
    print("train bmi lt25 ctrl")
    print(dim(tdt_bmi1[tdt_bmi1$CaseCtrl=="Ctrl",]))
    print("train bmi gte25 case")
    print(dim(tdt_bmi2[tdt_bmi2$CaseCtrl=="Case",]))
    print("train bmi gte25 ctrl")
    print(dim(tdt_bmi2[tdt_bmi2$CaseCtrl=="Ctrl",]))

    tdt_bmi1_perf <- roc(response=tdt_bmi1$CaseCtrl,predictor=tdt_bmi1$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    tdt_bmi2_perf <- roc(response=tdt_bmi2$CaseCtrl,predictor=tdt_bmi2$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig91 <- paste0(outfigprefix,".discovery.strata_BMIgroup.roc.pdf")
    pdf(outfig91,height=6.5,width=6.5)
    plot(tdt_bmi1_perf,col="#b3b3b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(tdt_bmi2_perf,col="#ffd92f",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("BMI < 25","BMI >= 25"),col=c("#b3b3b3","#ffd92f"),lwd=3,cex=1)
    dev.off()

    outfig92 <- paste0(outfigprefix,".discovery.strata_BMIgroup.boxplot.pdf")
    tdt$CaseCtrl <- factor(tdt$CaseCtrl,levels=c("Ctrl","Case"))
    tdt$BMIgroup <- factor(tdt$BMIgroup,levels=c("lt25","gte25"))
    pdf(outfig92,height=6.5,width=7.8)
    p92 <- ggplot(tdt,aes(x=BMIgroup,y=PEscore,fill=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"))+scale_fill_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+labs(x="BMI",y="cfDNAme score")+scale_x_discrete(labels=c("BMI < 25","BMI >= 25"))
    print(p92)
    dev.off()

    vdt_bmi1 <- subset(vdt,BMIgroup=="lt25")
    vdt_bmi2 <- subset(vdt,BMIgroup=="gte25")
    print("valid bmi lt25 case")
    print(dim(vdt_bmi1[vdt_bmi1$CaseCtrl=="Case",]))
    print("valid bmi lt25 ctrl")
    print(dim(vdt_bmi1[vdt_bmi1$CaseCtrl=="Ctrl",]))
    print("valid bmi gte25 case")
    print(dim(vdt_bmi2[vdt_bmi2$CaseCtrl=="Case",]))
    print("valid bmi gte25 ctrl")
    print(dim(vdt_bmi2[vdt_bmi2$CaseCtrl=="Ctrl",]))
    vdt_bmi1_perf <- roc(response=vdt_bmi1$CaseCtrl,predictor=vdt_bmi1$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    vdt_bmi2_perf <- roc(response=vdt_bmi2$CaseCtrl,predictor=vdt_bmi2$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig93 <- paste0(outfigprefix,".validation.strata_BMIgroup.roc.pdf")
    pdf(outfig93,height=6.5,width=6.5)
    plot(vdt_bmi1_perf,col="#b3b3b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(vdt_bmi2_perf,col="#ffd92f",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("BMI < 25","BMI >= 25"),col=c("#b3b3b3","#ffd92f"),lwd=3,cex=1)
    dev.off()

    outfig94 <- paste0(outfigprefix,".validation.strata_BMIgroup.boxplot.pdf")
    vdt$CaseCtrl <- factor(vdt$CaseCtrl,levels=c("Ctrl","Case"))
    vdt$BMIgroup <- factor(vdt$BMIgroup,levels=c("lt25","gte25"))
    pdf(outfig94,height=6.5,width=7.8)
    p94 <- ggplot(vdt,aes(x=BMIgroup,y=PEscore,fill=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"))+scale_fill_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+labs(x="BMI",y="cfDNAme score")+scale_x_discrete(labels=c("BMI < 25","BMI >= 25"))
    print(p94)
    dev.off()
    
    ##stratify by parity
    tdt_null <- subset(tdt,Obstretrical.history=="Nullip")
    tdt_multino <- subset(tdt,Obstretrical.history=="Multip-no PE")
    tdt_multiyes <- subset(tdt,Obstretrical.history=="Multip-PE")

    print("train null case")
    print(dim(tdt_null[tdt_null$CaseCtrl=="Case",]))
    print("train null ctrl")
    print(dim(tdt_null[tdt_null$CaseCtrl=="Ctrl",]))
    print("train multino case")
    print(dim(tdt_multino[tdt_multino$CaseCtrl=="Case",]))
    print("train multino ctrl")
    print(dim(tdt_multino[tdt_multino$CaseCtrl=="Ctrl",]))
    print("train multiyes case")
    print(dim(tdt_multiyes[tdt_multiyes$CaseCtrl=="Case",]))
    print("train multiyes ctrl")
    print(dim(tdt_multiyes[tdt_multiyes$CaseCtrl=="Ctrl",]))

    tdt_null_perf <- roc(response=tdt_null$CaseCtrl,predictor=tdt_null$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    tdt_multino_perf <- roc(response=tdt_multino$CaseCtrl,predictor=tdt_multino$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    tdt_multiyes_perf <- roc(response=tdt_multiyes$CaseCtrl,predictor=tdt_multiyes$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig31 <- paste0(outfigprefix,".discovery.strata_Parity.roc.pdf")
    pdf(outfig31,height=6.5,width=6.5)
    plot(tdt_null_perf,col="#b3b3b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(tdt_multino_perf,col="#ffd92f",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    plot(tdt_multiyes_perf,col="#a6d854",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.3,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("Nulliparity","Multiparity No PE","Multiparity had PE"),col=c("#b3b3b3","#ffd92f","#a6d854"),lwd=3,cex=1)
    dev.off()

    outfig32 <- paste0(outfigprefix,".discovery.strata_Parity.boxplot.pdf")
    ptdt <- subset(tdt,Obstretrical.history!="NA")
    ptdt$CaseCtrl <- factor(ptdt$CaseCtrl,levels=c("Ctrl","Case"))
    ptdt$Obstretrical.history <- factor(ptdt$Obstretrical.history,levels=c("Nullip","Multip-no PE","Multip-PE"))
    pdf(outfig32,height=6.5,width=7.8)
    p32 <- ggplot(ptdt,aes(x=Obstretrical.history,y=PEscore,fill=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"))+scale_fill_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+labs(x="Obstetric history",y="cfDNAme score")+scale_x_discrete(labels=c("Nulliparity","Multiparity No PE","Multiparity had PE"))
    print(p32)
    dev.off()


    vdt_null <- subset(vdt,Obstretrical.history=="Nullip")
    vdt_multino <- subset(vdt,Obstretrical.history=="Multip-no PE")
    vdt_multiyes <- subset(vdt,Obstretrical.history=="Multip-PE")
    vdt_null_perf <- roc(response=vdt_null$CaseCtrl,predictor=vdt_null$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    vdt_multino_perf <- roc(response=vdt_multino$CaseCtrl,predictor=vdt_multino$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    vdt_multiyes_perf <- roc(response=vdt_multiyes$CaseCtrl,predictor=vdt_multiyes$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    print("valid null case")
    print(dim(vdt_null[vdt_null$CaseCtrl=="Case",]))
    print("valid null ctrl")
    print(dim(vdt_null[vdt_null$CaseCtrl=="Ctrl",]))
    print("valid multino case")
    print(dim(vdt_multino[vdt_multino$CaseCtrl=="Case",]))
    print("valid multino ctrl")
    print(dim(vdt_multino[vdt_multino$CaseCtrl=="Ctrl",]))
    print("valid multiyes case")
    print(dim(vdt_multiyes[vdt_multiyes$CaseCtrl=="Case",]))
    print("valid multiyes ctrl")
    print(dim(vdt_multiyes[vdt_multiyes$CaseCtrl=="Ctrl",]))

    outfig41 <- paste0(outfigprefix,".validation.strata_Parity.roc.pdf")
    pdf(outfig41,height=6.5,width=6.5)
    plot(vdt_null_perf,col="#b3b3b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(vdt_multino_perf,col="#ffd92f",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    plot(vdt_multiyes_perf,col="#a6d854",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.3,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("Nulliparity","Multiparity No PE","Multiparity had PE"),col=c("#b3b3b3","#ffd92f","#a6d854"),lwd=3,cex=1)
    dev.off()

    outfig42 <- paste0(outfigprefix,".validation.strata_Parity.boxplot.pdf")
    pvdt <- subset(vdt,Obstretrical.history!="NA")
    pvdt$CaseCtrl <- factor(pvdt$CaseCtrl,levels=c("Ctrl","Case"))
    pvdt$Obstretrical.history <- factor(pvdt$Obstretrical.history,levels=c("Nullip","Multip-no PE","Multip-PE"))
    pdf(outfig42,height=6.5,width=7.8)
    p42 <- ggplot(pvdt,aes(x=Obstretrical.history,y=PEscore,fill=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"))+scale_fill_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+labs(x="Obstetric history",y="cfDNAme score")+scale_x_discrete(labels=c("Nulliparity","Multiparity No PE","Multiparity had PE"))
    print(p42)
    dev.off()

    ##stratify by IUGR
    itdt <- subset(tdt,IUGR=="Yes" | IUGR=="No")
    itdt_IUGRno <- subset(itdt,IUGR=="No")
    itdt_IUGRyes <- subset(itdt,IUGR=="Yes")

    itdt_IUGRno_perf <- roc(response=itdt_IUGRno$CaseCtrl,predictor=itdt_IUGRno$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    itdt_IUGRyes_perf <- roc(response=itdt_IUGRyes$CaseCtrl,predictor=itdt_IUGRyes$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig51 <- paste0(outfigprefix,".discovery.strata_IUGR.roc.pdf")
    pdf(outfig51,height=6.5,width=6.5)
    plot(itdt_IUGRno_perf,col="#b3b3b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(itdt_IUGRyes_perf,col="#ffd92f",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("Without IUGR","With IUGR"),col=c("#b3b3b3","#ffd92f"),lwd=3,cex=1)
    dev.off()

    outfig52 <- paste0(outfigprefix,".discovery.strata_IUGR.boxplot.pdf")
    itdt$CaseCtrl <- factor(itdt$CaseCtrl,levels=c("Ctrl","Case"))
    itdt$IUGR <- factor(itdt$IUGR,levels=c("No","Yes"))
    pdf(outfig52,height=6.5,width=7.8)
    p52 <- ggplot(itdt,aes(x=IUGR,y=PEscore,fill=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"))+scale_fill_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+labs(x="IUGR",y="cfDNAme score")+scale_x_discrete(labels=c("Without IUGR","With IUGR"))
    print(p52)
    dev.off()


    ivdt <- subset(vdt,IUGR=="Yes" | IUGR=="No")
    ivdt_IUGRno <- subset(ivdt,IUGR=="No")
    ivdt_IUGRyes <- subset(ivdt,IUGR=="Yes")

    ivdt_IUGRno_perf <- roc(response=ivdt_IUGRno$CaseCtrl,predictor=ivdt_IUGRno$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")
    ivdt_IUGRyes_perf <- roc(response=ivdt_IUGRyes$CaseCtrl,predictor=ivdt_IUGRyes$PEscore,ci=TRUE,levels=c("Ctrl","Case"),direction="<")

    outfig61 <- paste0(outfigprefix,".validation.strata_IUGR.roc.pdf")
    pdf(outfig61,height=6.5,width=6.5)
    plot(ivdt_IUGRno_perf,col="#b3b3b3",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.4,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5)
    plot(ivdt_IUGRyes_perf,col="#ffd92f",print.auc=TRUE,print.auc.x=0.4,print.auc.y=0.35,ci=TRUE,lwd=4,cex.lab=1.5,cex.axis=1.5,add=TRUE)
    legend("bottomright",legend=c("Without IUGR","With IUGR"),col=c("#b3b3b3","#ffd92f"),lwd=3,cex=1)
    dev.off()

    outfig62 <- paste0(outfigprefix,".validation.strata_IUGR.boxplot.pdf")
    ivdt$CaseCtrl <- factor(ivdt$CaseCtrl,levels=c("Ctrl","Case"))
    ivdt$IUGR <- factor(ivdt$IUGR,levels=c("No","Yes"))
    pdf(outfig62,height=6.5,width=7.8)
    p62 <- ggplot(ivdt,aes(x=IUGR,y=PEscore,fill=CaseCtrl))+geom_boxplot(position=position_dodge(1))+geom_dotplot(binwidth=0.01,dotsize=1.5,binaxis='y',stackdir='center',position=position_dodge(1))+theme_bw()+theme(axis.text.y=element_text(size=12,color="black"),axis.text.x=element_text(size=12,color="black"),legend.text=element_text(size=14),axis.title=element_text(size=14,color="black"))+scale_fill_manual(values=c("gray70","royalblue4"),name="Phenotype",labels=c("Control","Case"))+labs(x="IUGR",y="cfDNAme score")+scale_x_discrete(labels=c("Without IUGR","With IUGR"))
    print(p62)
    dev.off()
}

#plotstrataperf(infh,outfigprefix)
